### ISSUE TITLE
Mirror image on front camera

### ISSUE THREAD

**Issue by skeie** [react-native-community/react-native-camera#101]
Hi,

When picture is taken with the front camera, the image returned is mirrored. Is it possible to return the images 'as-is'? In other words, not mirrored?

**Comment by lwansbrough** [comment]
That's default behaviour of the camera. That functionality isn't currently supported but I'd accept a pull request!

**Comment by dhrrgn** [comment]
@lwansbrough @skeie It turns out we needed this feature, so... I submitted a PR for it :) (it is only for iOS  at the moment, see PR for reasoning): https://github.com/lwansbrough/react-native-camera/pull/212

**Comment by gaguirre** [comment]
Hi guys, we needed this feature for Android too so we implemented it.
We already submitted a PR #399

**Comment by brunolemos** [comment]
+1

Tried both combinations of `mirrorImage` but front camera pictures are always mirrored.

**Comment by gitlovenotwar** [comment]
I had the same issue, mirrorImage is being ignore. Front camera always return mirrored image.

**Comment by wassgha** [comment]
For me `mirrorImage` mirrors the image vertically rather than horizontally...

**Comment by arminsal1** [comment]
Any updates? I'm having the same issue.

**Comment by OrDuan** [comment]
Same issue here

**Comment by joecaraccio** [comment]
any progress on this?

**Comment by LarsWalter** [comment]
If someone is having trouble on Android with mirrorImage mirroring vertically rather than horizontally, you can try changing react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java line 42:
`m.preScale(-1, 1);`
to
`m.preScale(1, -1);`

Why this is the case I'm not sure. I'm guessing this has to do with what orientation you're taking a picture in, landscape or portrait.

Looking at iOS, I just added this little snippet into captureStill in RCTCameraManager line 644. Probably a better way to this other than through UIImage, but I know very little objective C, so this is what I ended up with.

```
  if (self.mirrorImage) {
    UIImage *tmpImg = [UIImage imageWithData: imageData];
    UIImage *flippedImage = [UIImage imageWithCGImage:tmpImg.CGImage
                                                scale:tmpImg.scale
                                          orientation:UIImageOrientationLeftMirrored];
    imageData = UIImageJPEGRepresentation(flippedImage, 1.0);
  }
```

If it flips the wrong direction, like those having issues with android, change out UIImageOrientationLeftMirrored with one of the others: https://developer.apple.com/documentation/uikit/uiimageorientation?language=objc

How one would fix this for video with front cam, I have no idea.

**Comment by joecaraccio** [comment]
yeah, this is great.

Trying to figure out how to fix it for video too however..

**Comment by monolithed** [comment]
Any updates?

**Comment by unicornRainbows** [comment]
Yeah mirrorImage flips it vertically, the fix in the MutableImage.java would work... but dont like hacking node_modules.. as we all know we going to have to npm install a few times in the RN lifecycle.. but hey thats why we do this shit.. cause normal coding is lame! 

"If you not living on the edge, you taking up too much space!"

**Comment by unicornRainbows** [comment]
This is the answer to fix android BUG or FEATURE.. Sometime i dont know if androids bugs are features... ;)

```<Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={
           { width: Metrics.screenWidth,
            height: Metrics.screenHeight,
            position:'absolute',
             top:0,
             left:0,
            backgroundColor: Colors.transparent}}
          aspect={Camera.constants.Aspect.fill}
type={"front"}
mirrorImage={true}
fixOrientation={true}
          captureTarget={Camera.constants.CaptureTarget.disk}
></Camera>```

Using both
**mirrorImage={true}
fixOrientation={true}**

will give you the desired effect!

Happy coding!

**Comment by OrDuan** [comment]
@unicornRainbows first it is deprecated.
second, the docs state:

> WARNING: It uses a significant amount of memory and my cause your application to crash if the device cannot provide enough RAM to perform the rotation. 

I hope the core dev will solve this issue internally without hack around, it's been here for more than 2 years :|

**Comment by facuescobar** [comment]
Did anyone solve this issue without using **fixOrientation={true}**, this works to me but as OrDuan said in last comment, it's deprecated and also has an important Warning message

**Comment by LarsWalter** [comment]
Seeing how this has gone unaddressed for 2 years, If you need this to be fixed I'd suggest you simply work around it yourself. I ended up writing a native module that rotates the image the way I needed using UIImage as described above for iOS and Bitmap + Matrix for Android. Writing something like that should be fairly straight forward for most I think. I just pass the image returned from the camera to my own module before I do anything else with it. It's not efficient, since now there's 2 separate image operations, but it does the job. I had to base64 encode the images anyways, so I just did it there.

An alternative to writing a module like this would be to fork the camera repo and do the changes I described above and just have your project sit on that fork.

As far as video goes, nobody has come up with anything as far as I can tell. The fixOrientation prop sounds like it only fixes images, but I haven't tried it.

**Comment by monolithed** [comment]
@LarsWalter Could you publish that package?

**Comment by monolithed** [comment]
```
mirrorImage={true}
fixOrientation={true}
```

This fix is not working for iPhone X!

**Comment by chtrinh** [comment]
For those trying to deal with images, this  as  style for your view works:
```
transform: [{ scaleX: -1 }]
```

**Comment by sibelius** [comment]
RNCamera has this prop as well

**Comment by Duya3fithou** [comment]
Now, I have not found a solution at all.Because RNCamera no longer uses the `mirrorImage` and `fixOrientation` properties Someone please help me, thanks..

**Comment by enaluz** [comment]
Flip the camera via styling. Just pass `transform: [{rotateY: '180deg'}]` to this style prop. My example:

```
      <RNCamera
        style={{ transform: [{rotateY: '180deg'}] }}
        type={RNCamera.Constants.Type.front}
        { ..props }
      />
```

Happy coding!

**Comment by timegambit** [comment]
Styling the camera is not a real solution because the picture is never mirrored.

Fix by adding the following code to line 752 of RNCamera.m:

```
if ([options[@"mirrorImage"] boolValue]) {
        [connection setVideoMirrored:true];
    }
```
Then take a mirrored image by calling takePictureAsync({mirrorImage: true})

**Comment by juliendevleeschauwer** [comment]
options = { quality: 1, exif: true, writeExif: true, mirrorImage: true, orientation: "portraitUpsideDown"}

**Comment by DB-009** [comment]
> options = { mirrorImage: true, orientation: "portraitUpsideDown"}

that didnt work

**Comment by juliendevleeschauwer** [comment]
> > options = { mirrorImage: true, orientation: "portraitUpsideDown"}
> 
> that didnt work
with this code my project works well 
cameraType : is a variable containing the type of RNCamera (front back)

const options = {
      mirrorImage: cameraType === RNCamera.Constants.Type.front ? true : false,
      orientation:
        cameraType === RNCamera.Constants.Type.front
          ? RNCamera.Constants.Orientation.portraitUpsideDown
          : RNCamera.Constants.Orientation.auto,
    };
    const cdata = await camera.current?.takePictureAsync(options);

**Comment by xRv9Fk0oQ6Da** [comment]
This still happens in 2022,
I think it's because it's an "inheriting permission". The user can set these Settings under their Camera app which for direct functions we'd have to have the granted Permissions inherited to them. If I find an update on this in my current DevSpace I'll post it here.

Remember, keep everyone updated! 🗡️

**Comment by siddharth-kt** [comment]
Hi @xRv9Fk0oQ6Da , 
any update ?

**Comment by xRv9Fk0oQ6Da** [comment]
> Hi @xRv9Fk0oQ6Da , 
> 
> any update ?

Nope. I just did the above method. Will continue my research when my Project resumes.

**Comment by DevSubhashis** [comment]
The ultimate Solution is for Andrloid

    `const options = { 
                quality: 0.5, 
                base64: true,
                mirrorImage: cameraType === RNCamera.Constants.Type.front ? true : false,
                orientation:
                    cameraType === RNCamera.Constants.Type.front
                    ? RNCamera.Constants.Orientation.portrait
                    : RNCamera.Constants.Orientation.auto,
             };
           
            const data = await cameraRef.current.takePictureAsync(options);`

**Comment by xRv9Fk0oQ6Da** [comment]
@DevSubhashis, have you tested the perspective, captured or selfie modes yet? Or does it still need Debugging?

**Comment by siddharth-kt** [comment]
Hi, @DevSubhashis @xRv9Fk0oQ6Da, in my case it didn't worked.
I needed to set {orientation: "portraitUpsideDown"} on selfie mode(front camera) to work correctly.

**Comment by xRv9Fk0oQ6Da** [comment]
> Hi, @DevSubhashis @xRv9Fk0oQ6Da, in my case it didn't worked.
> 
> I needed to set {orientation: "portraitUpsideDown"} on selfie mode(front camera) to work correctly.

You removed his accidental `` from the code, right? 

Oh. You got it working? No more mirroring?

**Comment by DevSubhashis** [comment]
> > Hi, @DevSubhashis @xRv9Fk0oQ6Da, in my case it didn't worked.
> > I needed to set {orientation: "portraitUpsideDown"} on selfie mode(front camera) to work correctly.
> 
> You removed his accidental `` from the code, right?

yes, its working on my phone, that's for code formatting in text editor also I only found solution for image, still trying for video

**Comment by siddharth-kt** [comment]
Yeah its working for me but with this code for front camera.
My orientation is different (not-portrait)
{
    mirrorImage: true,
    orientation: 'portraitUpsideDown',
    base64: false,
  };

**Comment by xRv9Fk0oQ6Da** [comment]
> > > Hi, @DevSubhashis @xRv9Fk0oQ6Da, in my case it didn't worked.
> 
> > > I needed to set {orientation: "portraitUpsideDown"} on selfie mode(front camera) to work correctly.
> 
> > 
> 
> > You removed his accidental `` from the code, right?
> 
> 
> 
> yes, its working on my phone, that's for code formatting in text editor also I only found solution for image, still trying for video 

If I remember right when I did mine like four years ago, I think I had to mirror the Video. But nothing else, just the View/Modal.

**Comment by siddharth-kt** [comment]
@DevSubhashis which android device did you tested on ? mine is vivo.
Our orientation in code is not same, different code is working for you and different is working for me so this might cause issues in production, that's why i am asking.
(look at this comment : https://github.com/react-native-camera/react-native-camera/issues/101#issuecomment-888032711)

also @xRv9Fk0oQ6Da what do you think ?

**Comment by DevSubhashis** [comment]
> > > > Hi, @DevSubhashis @xRv9Fk0oQ6Da, in my case it didn't worked.
> > 
> > 
> > > > I needed to set {orientation: "portraitUpsideDown"} on selfie mode(front camera) to work correctly.
> > 
> > 
> > > 
> > 
> > 
> > > You removed his accidental `` from the code, right?
> > 
> > 
> > yes, its working on my phone, that's for code formatting in text editor also I only found solution for image, still trying for video
> 
> If I remember right when I did mine like four years ago, I think I had to mirror the Video. But nothing else, just the View/Modal.

yes, for video the dirty solution is, add `transform: [{ scaleX: -1 }]` style to video component

**Comment by DevSubhashis** [comment]
> @DevSubhashis which android device did you tested on ? mine is vivo. Our orientation in code is not same, different code is working for you and different is working for me so this might cause issues in production, that's why i am asking. (look at this comment : [#101 (comment)](https://github.com/react-native-camera/react-native-camera/issues/101#issuecomment-888032711))
> 
> also @xRv9Fk0oQ6Da what do you think ?

for my phone its working, its realme 3i with android 10 version, i do't have any idea, if that will work on other devices. may be I enable base64 thats why this configuration working.

**Comment by siddharth-kt** [comment]
@DevSubhashis kindly check it  (if its because of base64 or not 🤔) and let me know.

**Comment by xRv9Fk0oQ6Da** [comment]
I think I finally came up with the solution here...  https://github.com/react-native-camera/react-native-camera/issues/101#issuecomment-888032711 has a pin-point concept; props @juliendevleeschauwer, in the issue each Developer is encountering an orientation difference all of which seem to be located in different parts of the world. It seems as if maybe the processor (intel), or other chips which may have their languages transversed could be related to an orientational difference. 

This isn't legit code, but a mere example to help understand what seems to be happening;

````
import { NativeModules, Platform } from 'react-native';

const deviceLanguage =
          Platform.OS === 'ios'
            ? NativeModules.SettingsManager.settings.AppleLocale ||
              NativeModules.SettingsManager.settings.AppleLanguages[0] // iOS 13
            : NativeModules.I18nManager.localeIdentifier;

console.log(deviceLanguage); //en_US
````

Users in Russia would contain devices with examples such as `en_RU`, India as such `en_IN` and further. 

Let me know how this works out as the solution for you all. 

For most accurate, please consult a Browser View Model while debugging (developing your app) because you're coding for cross-platform, not only one device. Rather have one device broke instead of all of them. 🙂

**Comment by siddharth-kt** [comment]
@xRv9Fk0oQ6Da yes https://github.com/react-native-camera/react-native-camera/issues/101#issuecomment-888032711
this comment solved my issue.
