### ISSUE TITLE
Issue when no focus on Android

### ISSUE THREAD

**Issue by viacheslav-gotsuliak** [react-native-community/react-native-camera#1044]
Hi there.

We're having strange issue with react-native-camera on Android. 
Capture promise never resolves when there is no focus on Android devices. To reproduce this issue it's enough to close camera and take photo. After that promise doesn't resolve (to then or error) even on photo with focus.

Maybe someone had something similar. 

Tested on Samsung Galaxy s7 with android 7.0.0, Samsung Note S8 with Android 7.0.0. Also this issue doesn't reproduce in debug mode.
react-native: 0.46.1

Update: tested on react-native 0.51.0 and still had that issue.

**Comment by eugene-zheng0208** [comment]
+1
same issue for me

**Comment by naddeoa** [comment]
I was able to debug this a little bit and narrowed it down to this line:

https://github.com/lwansbrough/react-native-camera/blob/master/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraModule.java#L559

Looks like there is a variable that needs to be switched but isn't for some reason.

**Comment by naddeoa** [comment]
Pretty sure it was caused by this commit:

https://github.com/lwansbrough/react-native-camera/commit/12afd8443ac3bb0aaaca17f2a11c349d81e465d1

Looks like there is some sequence of events that can result in the onPicuteTaken callback not getting called. A few other posts online about it, like this one: https://stackoverflow.com/questions/24917850/onpicturetaken-never-called

We'll need a better way to throttle the capture requests that doesn't involve setting a variable in a callback. If that was the intent.

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
