### ISSUE TITLE
CameraManager.Aspect on iOS

### ISSUE THREAD

**Issue by wassgha** [react-native-community/react-native-camera#1207]
### Which implementation are you using

RNCamera
(only imported RNCamera through `import {RNCamera} from 'react-native-camera'`

<img width="279" alt="screen shot 2018-02-02 at 9 47 29 am" src="https://user-images.githubusercontent.com/591655/35738976-489a5bfe-07fe-11e8-8c47-f405c36d000d.png">

**Comment by sibelius** [comment]
This happen when the link is wrong

**Comment by dann1609** [comment]
do a manual link:

1) npm install react-native-camera --save
2) In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
3) Go to node_modules ➜ react-native-camera and add RNCamera.xcodeproj
4) In XCode, in the project navigator, select your project. Add libRNCamera.a to your project's Build Phases ➜ Link Binary With Libraries
5) Click RNCamera.xcodeproj in the project navigator and go the Build Settings tab. Make sure 'All' is toggled on (instead of 'Basic'). In the Search Paths section, look for Header Search Paths and make sure it contains both $(SRCROOT)/../../react-native/React and $(SRCROOT)/../../../React - mark both as recursive.

**Comment by tiagoalucard** [comment]
expo bro! no need Mac

**Comment by Dabbous1** [comment]
> do a manual link:
> 
> 1. npm install react-native-camera --save
> 2. In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
> 3. Go to node_modules ➜ react-native-camera and add RNCamera.xcodeproj
> 4. In XCode, in the project navigator, select your project. Add libRNCamera.a to your project's Build Phases ➜ Link Binary With Libraries
> 5. Click RNCamera.xcodeproj in the project navigator and go the Build Settings tab. Make sure 'All' is toggled on (instead of 'Basic'). In the Search Paths section, look for Header Search Paths and make sure it contains both $(SRCROOT)/../../react-native/React and $(SRCROOT)/../../../React - mark both as recursive.

What files do you add exactly?

**Comment by n1ru4l** [comment]
@Dabbous1 The ones mentioned in Step 3
