### ISSUE TITLE
Different argument structure of event onBarCodeRead on iOS and Android

### ISSUE THREAD

**Issue by anchoretics** [react-native-community/react-native-camera#1216]
### Which implementation are you using

RCTCamera or RNCamera?
RNCamera
### Steps to reproduce
1.barCodeTypes={[Camera.constants.BarCodeType.qr]}
2.onBarCodeRead={this.onBarCodeRead.bind(this)}
3.Scan a QR Code on iOS and android device

### Expected behaviour
the argument of event onBarCodeRead, should be the structure as follows:
```
{
    data: "https://xxx.xxx",
    type: "QR_CODE",
    bounds: {
        origin: {x:0, y:0},
        size: {height: 0, width: 0}
    }
}
```

### Actual behaviour
the onBarCodeRead's argument is expected on iOS,
but it's anothor structure on android device:
```
{
    data: "https://xxx.xxx",
    type: "QR_CODE",
    bounds: [
        {x:0, y:0},
        {x:0, y:0},
        {x:0, y:0},
        {x:0, y:0}
    ]
}
```
and there's no related document about this,
is this a BUG?
whatever, there shoud be a detailed description aboud onBarCodeRead and it's arguments.

### Environment
- **Node.js version**: 8.9.3
- **React Native version**: 0.52.0
- **React Native platform + platform version**: iOS 11.2, Android 5.1

### react-native-camera
**Version**: 0.13.0

**Comment by jgfidelis** [comment]
Are you on master or v0.13.0? You cannot use RNCamera on 0.13. You must be using RCTCamera then.

**Comment by anchoretics** [comment]
@jgfidelis tks, i changed to RNCamera, bu onBarCodeRead's argument donot have bounds anymore,
I just need the bounds to check that if the scaned QRcode is inside the area of my customer mark as blow:
![WechatIMG25.png](https://i.loli.net/2018/02/07/5a7acfbcd3d1b.png)

**Comment by n1ru4l** [comment]
Seems like a feature request for RNCamera! Feel free to send a pull request that implements the bounds for `RNCamera`

**Comment by SimonErm** [comment]
@n1ru4l  Yes, the actual behaviour is the expected behaviour. Like said in the discription of  #1402 (@sash ) , Android and iOS returns different bounds since ZXing returns no real bounds, but ResultPoints (https://zxing.github.io/zxing/apidocs/com/google/zxing/ResultPoint.html). I though that this already was added to the docs, so i will make a PR.

**Comment by SimonErm** [comment]
@anchoretics which version of react-native-camera are you using?

**Comment by n1ru4l** [comment]
@SimonErm Can't we convert the android bounds to the ios equivalent?

**Comment by SimonErm** [comment]
@n1ru4l  We could test, which codes deliver which resultPoints and calculate the origin and size before emitting the event. The bounds wouldn't be exact since the resultPoints don't deliver data to calculate the barcode heights and the QR-Corners are not the outer corners, but i think it would be more convenient for the user to handle iOS and Android the same way.

**Comment by SimonErm** [comment]
I will try to do this at the weekend

**Comment by SimonErm** [comment]
I worked on it, but i don't think this is the solution, because the 2D codes returning different ResultPoints
