### ISSUE TITLE
undefined is not an object 'CameraManager.Aspect.Fill'

### ISSUE THREAD

**Issue by luisrodge** [react-native-community/react-native-camera#1735]
react-native-camera 1.1.4 android

For some reason I keep getting the aforementioned error on android when running the app on my device.
There is no way to get rid of the error other than reinstalling the app entirely.

**Comment by sibelius** [comment]
this looks like a linking issue

**Comment by luisrodge** [comment]
I have done everything according to the documentation.

**Comment by patt-makeitsimple** [comment]
Have you console.log(CameraModule) in Camera.js? 
I have the same issue, this will get error randomly. Because I have also installed react-native-camera-kit, I try to add a new function in react-native-camera-kit CameraModule.java , e.g.
    
@ReactMethod
public void cameraKitByTrial() {

} 

After clean gradle and run again, I found the cameraKitByTrial function will be printed out in console.log . That mean the CameraModule loaded in Camera.js is the module from react-native-camera-kit. This is because their module name CameraModule are the same. 

To solve it, I rename the module name in RCTCamera.java getName method to RCTCameraModuleDeprecated and change the NativeModules.CameraModule to NativeModules.CameraModuleDeprecated. The error then gone.

**Comment by SimonErm** [comment]
can this be closed?

**Comment by sibelius** [comment]
relink properly

**Comment by olanMbakop** [comment]
> Have you console.log(CameraModule) in Camera.js?
> I have the same issue, this will get error randomly. Because I have also installed react-native-camera-kit, I try to add a new function in react-native-camera-kit CameraModule.java , e.g.
> 
> @ReactMethod
> public void cameraKitByTrial() {
> 
> }
> 
> After clean gradle and run again, I found the cameraKitByTrial function will be printed out in console.log . That mean the CameraModule loaded in Camera.js is the module from react-native-camera-kit. This is because their module name CameraModule are the same.
> 
> To solve it, I rename the module name in RCTCamera.java getName method to RCTCameraModuleDeprecated and change the NativeModules.CameraModule to NativeModules.CameraModuleDeprecated in Camera.js. The error then gone.

Hi, I have the same issue. Can you elaborate more on the procedure you used? ie. Steps.

I'm stuck in here `RCTCamera.java getName`
