### ISSUE TITLE
How to identify the QR code in the album

### ISSUE THREAD

**Issue by zhuiye** [react-native-community/react-native-camera#1906]
Now I have a need, I need to select the QR code image from the album, and then identify the information, but I don't know how to do it. Do you have any good ideas?

**Comment by n1ru4l** [comment]
This seems out of scope of this library. Please use StackOverflow for posting general questions.

Nevertheless I gave google a spin and found this:

https://stackoverflow.com/questions/51920987/qr-code-decoder-from-image-file-react-native

If you want a truly native solution you will most likely have to write your own native module.

I am going to close this issue because it is not related to react-native-camera and does not follow the issue template.
