### ISSUE TITLE
Zooming not functional on Android(?)

### ISSUE THREAD

**Issue by Jacob-Finn** [react-native-community/react-native-camera#2537]
# Bug Report

**To Do First**

- [X] Did you try latest release?
- [X] Did you try master?
- [X] Did you look for existing matching issues?

**Platforms**

Android: Samsung Galaxy S9+
iOS: iPhone 7

**Versions**

Android: 9
iOS: 12.4
react-native-camera: 3.7.1
react-native: 0.60.5
react: 16.8.6
react-navigation: 3.11.1

**Description/Current Behaviour**
Incrementing the zoom prop of the RNCamera component via a state change doesn't change the zoom level on Android but works perfectly fine on iOS.

**Expected Behaviour**

Incrementing the zoom prop of the RNCamera should cause the zoom to change on both iOS and Android

**Steps to Reproduce**
- Assign the zoom prop to a state variable
- Increase/decrease the zoom prop in a state change
- Android will not be affected, iOS will either zoom in or zoom out.

**Additionals**

Related code snippets:
https://pastebin.com/cuYDDKKN
(Moved to pastebin for actual readable format)

**Comment by cristianoccazinsp** [comment]
A 0.001 zoom increment won't do much on Android. The value must be between 0 and 1, being 1 100% zoom and 0 0% zoom.
On iOS, zoom behaves very oddly (because the zoom values can be extremely high), so you will definitely see a zoom change even with 0.001.

For both iOS and Android consistency, I recommend setting the `maxZoom` prop to 8 or 16 (this is for iOS only) which is the standard digital zoom value. Then, increment your zoom value by either 0.1 or 0.01, both should definitely work depending on how "smooth" you want the zooming in to happen if you are using pinch to zoom.

**Comment by Jacob-Finn** [comment]
@cristianoccazinsp Thanks for the advice! Unfortunately, in order to get a smooth experience I ended up keeping track of zoom separately depending on if the os was Android or iOS.
