### ISSUE TITLE
Uploading Video to Firebase Storage as mp4

### ISSUE THREAD

**Issue by ChristopherJohnson25** [react-native-community/react-native-camera#2545]
# Question

Does anyone have any experience uploading a video to Firebase storage as an mp4? I'm streaming videos with VideoJS and it will not play .mov. Nor will react native video stream as far as I can tell. Any ideas?

**Comment by olinations** [comment]
In most cases you can simply change the .mov extension to the .mp4 extension . No need to convert the file because .mov is a wrapper for what is already a .mp4 so it will play just the same with the .mp4 extension.

I have done this and it seems to have worked on my devices, but I have not tested on all devices, may be worth a shot before diving into converting video formats.

**Comment by ChristopherJohnson25** [comment]
Unfortunately, simply changing the extension does not work (the file still works as .mp4, but it cannot get played by Chrome or Video.JS). I suspect that Video.JS is referencing the  mime type? I'm currently working on trying to change that via blob, but having some troubles.

**Comment by igor-lemon** [comment]
@ChristopherJohnson25 Yes. Just use ffmpeg library for processing videos
https://github.com/tanersener/react-native-ffmpeg

**Comment by sibelius** [comment]
can someone add a section on our documentation about this?

**Comment by ChristopherJohnson25** [comment]
Thanks @igor-lemon, I will look into this.

**Comment by Bilal112** [comment]
!
![image](https://user-images.githubusercontent.com/23139110/71370931-4f79db00-25d1-11ea-89b5-61f9b605d085.png)
   its done
