### ISSUE TITLE
AVCaptureSessionPresetPhoto not supported during face detection. Falling back to AVCaptureSessionPresetHigh

### ISSUE THREAD

**Issue by noor94Test** [react-native-community/react-native-camera#2595]
the FaceDetector.detectFacesAsync is not working on the following devices :
iPhone Xr Red / iOS 12 and iPhone XS max /iOS 13.2

const checkIfPictureContainFace = await FaceDetector.detectFacesAsync(
      data.uri
    );
error:
AVCaptureSessionPresetPhoto not supported during face detection. Falling back to AVCaptureSessionPresetHigh

**Comment by sibelius** [comment]
Can u send a pull request fixing it?

**Comment by noor94Test** [comment]
@sibelius I am asking for a fix for this issue.

**Comment by sibelius** [comment]
let us know when you fix it

**Comment by noor94Test** [comment]
We are not able to fix this issue, we are asking for someone smart to help us!!

**Comment by cristianoccazinsp** [comment]
The log is just a warning/log from here https://github.com/react-native-community/react-native-camera/blob/master/ios/RN/RNCamera.m#L1407

While I don't know the specific details about why that constraint is needed, it should be just a warning. 

I haven't used face detection myself so I'm not sure what's the issue. If you want to prevent the warning from happening, you could try with `pictureSize="High"` (iOS only). That would put the camera into the right capture mode (at the risk of losing photo quality) and silence the warning, but I don't think it would change much since that's what the native code already does.

Have you followed everything from the install instructions for face detection?

**Comment by lucastonon** [comment]
Setting pictureSize="High" stops the warning but face detector still won't work

**Comment by lucastonon** [comment]
> Closing this issue after a prolonged period of inactivity. Fell free to reopen this issue, if this still affecting you.
Setting pictureSize="High" stops the warning but face detector still won't work

**Comment by lucastonon** [comment]
> Closing this issue after a prolonged period of inactivity. Fell free to reopen this issue, if this still affecting you.

Setting pictureSize="High" stops the warning but face detector still won't work
