### ISSUE TITLE
How to adjust recorded video width and height for playback?

### ISSUE THREAD

**Issue by ysrarff** [react-native-community/react-native-camera#2772]
# Question

**To Do First**
- [X] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [X] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

Hi, I'm still a React Native newbie. Need to know if there is any way to adjust the recorded video's dimensions manually (i.e. setting specific width and height for all recorded videos) so that my app could deliver constant playback quality?

As far as I'm concern, in the docs, we could only set the Video Quality and bitrate as well as the codec and (pls correct me if im wrong but) all of this relates to the quality and not the dimensions themselves. Need assistance with this, thank you for this awesome package! 

**Tags**

Video, Width, Height, Dimensions 

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cristianoccazinsp** [comment]
I don't think you can modify the video width/height easily. You should pick a resolution/aspect ratio (e.g., 720 or or 480p) and adjust your UI for that. Video players (such as react-native-video) should be able to handle playback properly.

If your goal is to just play any aspect ratio, then you should probably ask this at react-native-video since playback is not part of the camera.
