### ISSUE TITLE
Streaming from camera

### ISSUE THREAD

**Issue by evanlarkin10** [react-native-community/react-native-camera#2869]
Is there any way to stream from the camera feed to an rtmp endpoint?

**Comment by renatobenks** [comment]
In order to support that, and make it works, I was wondering about how it could be done. So maybe, would be quite useful to know more about what you would like to do with that, to understand better why did you come up to us with that. Because it probably will help us to think greater on this, and define precisely how it should be looks like. So, could you provide that for us?
