### ISSUE TITLE
Feature request: Real-time Preview Processing

### ISSUE THREAD

**Issue by kayazinc** [react-native-community/react-native-camera#689]
#### Use-case
While in camera preview mode, it is able to detect object such as "Rectangle" or "Facial" and draw a rectangle around the object.

Is it possible to achieve the use-case in javascript, such as having a new onPreivew() method that returns the image and then perform the detection algorithm on the image?

Thanks, any advice are welomed.

**Comment by dotnetprofessional** [comment]
I'd like to add to this - I'm currently attempting to add an event that returns the preview image so that additional processing can be done. Taking captures is just too slow on Android (iOS is fairly quick). On Android this looks to be fairly straightforward as the byte[] is available, but for iOS its seems a bit more involved. Though any pointers are welcome, as Obj-C isn't a language I know :)

**Comment by npomfret** [comment]
@dotnetprofessional  Have you tried master?  There are some changes which may improve capture performance on android that I don't think have been released yet.

The iOS version of the android byte[] is [here](https://github.com/lwansbrough/react-native-camera/blob/master/ios/RCTCameraManager.m#L590) i think.

**Comment by dotnetprofessional** [comment]
@npomfret Thanks for the details - I've not tried master. I took a look at the iOS link you gave me, but that's if you do a capture. I'm looking at getting the byte[] from a preview so that its really fast. My scenario (which is odd I'll admit) is to capture the video preview and save the image as a JPG so that a webview can keep refreshing it. The idea is to provide a pysdo stream within a webview ie a web page. We can use WebRTC on Android but iOS doesn't support that.

**Comment by barron9** [comment]
please take a look at anyline ocr react-native demo for this

**Comment by dotnetprofessional** [comment]
@barron9 Thanks but the pricing model would bankrupt us given our product.

**Comment by npomfret** [comment]
What are the rules regarding plugging commercial products on here?

**Comment by barron9** [comment]
no just take the idea, their custom camera draws rectangles around objects words etc in every 10 or 20 ms. to recognize cam refreshes itself so processes while on preview

**Comment by cesarve77** [comment]
+1

**Comment by sibelius** [comment]
@dbishai is this https://github.com/dbishai/react-native-camera/commit/75553a6a1d09842558ad16fd6cb16abcd67cdcad performa performatic?

**Comment by dbishai** [comment]
@sibelius, what does "performa performatic" mean?

**Comment by ducpt2** [comment]
+ 1.

**Comment by rafaelcavalcante** [comment]
This should be reopened

Related: #2984
