### ISSUE TITLE
Can you support to CRNA

### ISSUE THREAD

**Issue by lslvxy** [react-native-community/react-native-camera#784]
Can you support to project created by [create-react-native-app]( https://github.com/react-community/create-react-native-app)

it canot run `react-native link` to link

**Comment by hedgerh** [comment]
@lslvxy I'm guessing there's no way for them to make `react-native-camera` work with CRNA, since `react-native-camera` relies on native code, and, like you mentioned, CRNA/Expo do not support linking of native code.

Any native functionality when using CRNA/Expo is provided by the Expo SDK.  Unfortunately, flexible camera/video capture functionality hasn't been implemented in the SDK, yet, but it is being worked on.  Looks like it will be in Expo SDK 20, around August:  https://expo.canny.io/feature-requests/p/camera-component
